### ISSUE TITLE
NLU Java is missing.

### ISSUE THREAD

**Issue by ujja** [schul-cloud/cui#5]
Hello

Very good repo. 

But it does not work for me. I got exception from NLU at start:

```
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-] 2018-08-24 09:39:34 ERROR    __main__  - [Errno 2] No such file or directory: '/usr/lib/jvm'
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-] Traceback (most recent call last):
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/server.py", line 241, in parse
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     self.data_router.parse, data))
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     result = inContext.theWork()
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     return func(*args,**kw)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/data_router.py", line 241, in parse
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     model)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/project.py", line 118, in parse
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     interpreter = self._interpreter_for_model(model_name)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/project.py", line 198, in _interpreter_for_model
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     return Interpreter.create(metadata, self._component_builder)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/model.py", line 303, in create
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     model_metadata, **context)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/components.py", line 398, in load_component
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     cached_component, **context)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/registry.py", line 131, in load_component_by_name
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     return component_clz.load(model_dir, metadata, cached_component, **kwargs)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/duckling_extractor.py", line 194, in load
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     duckling = cls.create_duckling_wrapper(language)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/extractors/duckling_extractor.py", line 108, in create_duckling_wrapper
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     return DucklingWrapper(language=language)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/duckling/wrapper.py", line 35, in __init__
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     maximum_heap_size=maximum_heap_size)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/duckling/duckling.py", line 44, in __init__
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     self._start_jvm(minimum_heap_size, maximum_heap_size)
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/duckling/duckling.py", line 69, in _start_jvm
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     jpype.getDefaultJVMPath(),
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/jpype/_core.py", line 121, in get_default_jvm_path
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     return finder.get_jvm_path()
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/jpype/_jvmfinder.py", line 131, in get_jvm_path
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     jvm = method()
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/jpype/_jvmfinder.py", line 184, in _get_from_known_locations
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     for home in self.find_possible_homes(self._locations):
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]   File "/usr/local/lib/python3.6/site-packages/jpype/_jvmfinder.py", line 97, in find_possible_homes
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-]     for childname in sorted(os.listdir(parent)):
rasa-nlu_1           | 2018-08-24 09:39:34+0000 [-] FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/jvm'

```

And fix in `cui\rasa_nlu\Dockerfile` is:

```
SHELL ["/bin/bash", "-c"]

# required for Java
# see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
RUN mkdir -p /usr/share/man/man1   <--------------------------- Change 1, see comment above
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    build-essential \
    git-core \
    openssl \
    libssl-dev \
    libffi6 \
    libffi-dev \
    curl \
	cron \
#required for duckling.
    default-jre \   <--------------------------- Change 2, see comment above
....
```

**Comment by janrenz** [comment]
Please feel free to submit a PR ...
